// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqmxYP5WA34AuiCsdXhT_NWHmRalVo9vA',
    appId: '1:307297168024:web:23104d33a74c1458b07eed',
    messagingSenderId: '307297168024',
    projectId: 'gymapp-4c108',
    authDomain: 'gymapp-4c108.firebaseapp.com',
    storageBucket: 'gymapp-4c108.firebasestorage.app',
    measurementId: 'G-9DCEC6KYV0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA25xHaeky5FaHP_N_gnC6E83m3Rdu1lGE',
    appId: '1:307297168024:android:1c255904ee824ea9b07eed',
    messagingSenderId: '307297168024',
    projectId: 'gymapp-4c108',
    storageBucket: 'gymapp-4c108.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRpYqsj1o1BqrswPl0GM8g27Ewv8BI2Vc',
    appId: '1:307297168024:ios:622fa24aa22f4470b07eed',
    messagingSenderId: '307297168024',
    projectId: 'gymapp-4c108',
    storageBucket: 'gymapp-4c108.firebasestorage.app',
    iosBundleId: 'com.coursestore.courseStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRpYqsj1o1BqrswPl0GM8g27Ewv8BI2Vc',
    appId: '1:307297168024:ios:622fa24aa22f4470b07eed',
    messagingSenderId: '307297168024',
    projectId: 'gymapp-4c108',
    storageBucket: 'gymapp-4c108.firebasestorage.app',
    iosBundleId: 'com.coursestore.courseStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqmxYP5WA34AuiCsdXhT_NWHmRalVo9vA',
    appId: '1:307297168024:web:f2a97bc5fe5dfc06b07eed',
    messagingSenderId: '307297168024',
    projectId: 'gymapp-4c108',
    authDomain: 'gymapp-4c108.firebaseapp.com',
    storageBucket: 'gymapp-4c108.firebasestorage.app',
    measurementId: 'G-MJT87805CG',
  );
}
